import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#454744",
        "tertiary-container": "#1c1b1a",
        "surface-bright": "#faf9f9",
        "tertiary-fixed-dim": "#cac6c4",
        "primary-fixed": "#e5e2e1",
        "on-secondary-fixed": "#1a1c19",
        "on-tertiary-container": "#868382",
        "on-background": "#1b1c1c",
        "tertiary-fixed": "#e6e2df",
        "secondary": "#5d5f5b",
        "surface-container": "#efeded",
        "background": "#faf9f9",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e2e2",
        "secondary-fixed-dim": "#c6c7c2",
        "surface-container-highest": "#e3e2e2",
        "on-primary-container": "#858383",
        "on-error-container": "#93000a",
        "primary-container": "#1c1b1b",
        "tertiary": "#000000",
        "primary": "#000000",
        "error": "#ba1a1a",
        "secondary-fixed": "#e2e3de",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container-low": "#f4f3f3",
        "on-primary-fixed": "#1c1b1b",
        "secondary-container": "#e2e3de",
        "surface-dim": "#dbdad9",
        "inverse-primary": "#c8c6c5",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474746",
        "surface-tint": "#5f5e5e",
        "on-surface": "#1b1c1c",
        "outline-variant": "#c4c7c7",
        "outline": "#747878",
        "on-tertiary-fixed": "#1c1b1a",
        "on-tertiary-fixed-variant": "#484645",
        "on-error": "#ffffff",
        "surface-container-high": "#e9e8e8",
        "inverse-surface": "#2f3031",
        "on-secondary-container": "#636561",
        "surface": "#faf9f9",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444748",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "ma-unit": "1rem",
        "gutter": "2rem",
        "element-gap": "4rem",
        "margin-page": "5vw",
        "section-gap": "24rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-newsreader)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-xl": ["var(--font-newsreader)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-newsreader)", "serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.8", fontWeight: "400" }],
        "headline-xl": ["84px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "body-lg": ["18px", { lineHeight: "1.9", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      maxWidth: {
        "8xl": "88rem",
      },
    },
  },
  plugins: [],
};

export default config;
